### ISSUE TITLE
How to construct the trajectory-based region graph?

### ISSUE THREAD

**Issue by csjiezhao** [HKUDS/AutoST#2]
I do not seem to find the corresponding code in file `pre_spatial_graph.py`.

**Comment by lizzyhku** [comment]
Hi,
Thanks a lot for your interest in our paper.
I am sorry for my late reply.
The code for constructing a trajectory-based region graph can be found in the pre_s3.py file, specifically from line 84 to line 100.
If you have any further questions or need additional clarification, please don't hesitate to let me know.
Thank you once again for your interest, and I look forward to addressing any remaining queries you may have.
